# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Simple forum
brief-intro: Learn something deep, than you can see somethinf different!
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://jacobpan3g.github.io" # the base hostname & protocol for your site

motto: Follow Excellence. Success will chase you!

description_footer: Let's work together

permalink: /:year/:month/:day/:title/

# other links
#twitter_username: gaohaoyang126
#facebook_username: gaohaoyang.water
github_username:  ydlNAU
email: yudalang2017@sibs.ac.cn
#weibo_username: 3115521wh
#zhihu_username: gaohaoyang
#linkedIn_username: gaohaoyang
#dribbble_username:

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
#duoshuo_shortname: #hygblog
#disqus_shortname: gaohaoyang

#gitment
comment_gitment_repo: MathSimpleForum
comment_gitment_clientId: b68c3af4470cd0543e8e
comment_gitment_clientSecret: 1da2b0f277a2672c67037db98586d11dbfbd93f2

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 0489654452e74cfa7bed5e55504bdeee
#google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

#kramdown:
#  input: GFM
#  syntax_highlighter: rouge
## From http://blog.javachen.com/2015/06/30/jekyll-kramdown-config.html
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart


# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
